[package]
name = "kuu_er"
version = "0.1.0"
authors = ["Han Kruiger <HanKruiger@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
qrcodegen = "1.8.0"
wasm-bindgen = "0.2.87"

[dependencies.web-sys]
version = "0.3.64"
