[package]
name = "kuu_er"
version = "0.1.0"
authors = ["Han Kruiger <HanKruiger@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
qrcodegen = "1.6.0"
wasm-bindgen = "0.2.63"

[dependencies.web-sys]
version = "0.3.40"